# A file defines the map program languages to their extend names.
# The default colors comes from GitHub Linguist colors(https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml)

skip_exts: [".lock", ".lock.json", "LICENSE", ""]
skip_languages: 
  - "JSON"
  - "YAML"
  - "TOML"
  - "XML"
  - "Markdown"
  - "Unknown"

languages:
  # Python
  "Python":
    exts: [".py", ".pyd", ".pyi"]
    color: "#3572a5"

  # JavaScript / TypeScript
  "JavaScript":
    exts: [".js", ".jsx"]
    color: "#f1e05a"

  "TypeScript":
    exts: [".ts", ".tsx"]
    color: "#3178c6"

  # Java / Kotlin
  "Java":
    exts: [".java"]
    color: "#b07219"

  "Kotlin":
    exts: [".kt", ".kts"]
    color: "#A97BFF"

  # C family
  "C":
    exts: [".c", ".h"]
    color: "#555555"

  "C++":
    exts: [".cpp", ".hpp", ".cc", ".cxx"]
    color: "#f34b7d"

  "Objective-C":
    exts: [".m", ".mm"]
    color: "#c84e2b"

  "C#":
    exts: [".cs"]
    color: "#178600"

  # Rust / Go
  "Rust":
    exts: [".rs"]
    color: "#dea584"

  "Go":
    exts: [".go"]
    color: "#00ADD8"

  # Ruby / Lua / PHP
  "Ruby":
    exts: [".rb"]
    color: "#701516"

  "Lua":
    exts: [".lua"]
    color: "#000080"

  "PHP":
    exts: [".php"]
    color: "#4F5D95"

  # Web
  "HTML":
    exts: [".html", ".htm"]
    color: "#e34c26"

  "CSS":
    exts: [".css"]
    color: "#663399"

  "SCSS":
    exts: [".scss"]
    color: "#c6538c"

  "VUE":
    exts: [".vue"]
    color: "#41b883"

  # Docs
  "Markdown":
    exts: [".md"]
    color: "#083fa1"

  # Data Formats
  "JSON":
    exts: [".json"]
    color: "#292929"

  "YAML":
    exts: [".yaml", ".yml"]
    color: "#cb171e"

  "TOML":
    exts: [".toml"]
    color: "#9c4221"

  "XML":
    exts: [".xml"]
    color: "#0060ac"

  # scripts
  "Shell":
    exts: [".sh", ".bash", ".zsh"]
    color: "#89e051"

  "PowerShell":
    exts: [".ps1"]
    color: "#012456"

  # sql
  "SQL":
    exts: [".sql"]
    color: "#e38c00"
  
  # docker
  "Dockerfile":
    exts: [".Dockerfile", ".dockerfile"]
    color: "#384d54"

  "Unknown":
    exts: []
    color: "#ededed"
